### ISSUE TITLE
Glow support on Paper 1.21.3

### ISSUE THREAD

**Issue by mizuo-san** [Norbit4/TreeCuter#10]

**Comment by epifeny** [comment]
+1 please make this work on Paper 1.21.3
```
[09:07:43 INFO] Enabling TreeCuter vv1.8.5
[09:07:43 INFO] [GlowingEntities] Found server version 1.21.3
[09:07:43 INFO] [GlowingEntities] Loaded transparent mappings.
[09:07:43 ERROR] [GlowingEntities] Glowing Entities reflection failed to initialize. The util is disabled. Please ensure your version (1.21.3-R0.1-SNAPSHOT) is supported.
[09:07:43 INFO] java.lang.reflect.InvocationTargetException: null
[09:07:43 INFO] at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:72) ~[?:?]
[09:07:43 INFO] at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
[09:07:43 INFO] at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
[09:07:43 INFO] at TreeCuter-v1.8.5.jar/fr.skytasul.reflection.TransparentReflectionAccessor$TransparentConstructor.newInstance(TransparentReflectionAccessor.java:157) ~[?:?]
[09:07:43 INFO] at TreeCuter-v1.8.5.jar/fr.skytasul.glowingentities.GlowingEntities$Packets.loadReflection(GlowingEntities.java:447) ~[?:?]
[09:07:43 INFO] at TreeCuter-v1.8.5.jar/fr.skytasul.glowingentities.GlowingEntities$Packets.initialize(GlowingEntities.java:421) ~[?:?]
[09:07:43 INFO] at TreeCuter-v1.8.5.jar/fr.skytasul.glowingentities.GlowingEntities$Packets.ensureInitialized(GlowingEntities.java:366) ~[?:?]
[09:07:43 INFO] at TreeCuter-v1.8.5.jar/fr.skytasul.glowingentities.GlowingEntities.<init>(GlowingEntities.java:58) ~[?:?]
[09:07:43 INFO] at TreeCuter-v1.8.5.jar/fr.skytasul.glowingentities.GlowingBlocks.<init>(GlowingBlocks.java:43) ~[?:?]
[09:07:43 INFO] at TreeCuter-v1.8.5.jar/pl.norbit.treecuter.utils.GlowUtils.init(GlowUtils.java:46) ~[?:?]
[09:07:43 INFO] at TreeCuter-v1.8.5.jar/pl.norbit.treecuter.TreeCuter.onEnable(TreeCuter.java:31) ~[?:?]
[09:07:43 INFO] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
[09:07:43 INFO] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21.3-R0.1-SNAPSHOT.jar:?]
[09:07:43 INFO] at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:655) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:604) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:768) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:530) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:326) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:340) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[09:07:43 INFO] Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.paperConfig()" because "world" is null
[09:07:43 INFO] at net.minecraft.world.entity.Entity.<init>(Entity.java:574) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at net.minecraft.world.entity.Marker.<init>(Marker.java:18) ~[paper-1.21.3.jar:1.21.3-81-da71382]
[09:07:43 INFO] at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
[09:07:43 INFO] ... 22 more
[09:07:43 WARN] Glowing is not supported on this server version: 1.21.3-81-da71382 (MC: 1.21.3)
[09:07:43 WARN] Suported ver: [1.17.1, 1.18.2, 1.19.4, 1.20.2, 1.20.4, 1.20.5, 1.20.6, 1.21]
[09:07:43 WARN] Suported engines: Paper and forks
[09:07:43 WARN] [Server thread/WARN]:
[09:07:43 INFO] [Server thread/INFO]:
[09:07:43 INFO] TreeCuter by Norbit4!
```

**Comment by Norbit4** [comment]
Added!
